import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carrot Market",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-neutral-900 text-white max-w-sm mx-auto`}>{children}</body>
    </html>
  );
}
